# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'
  # vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

# This specific SDK is needed for the integration tests
- task: DotNetCoreInstaller@0
  displayName: Install ASP.NET Core SDK
  inputs:
    packageType: 'sdk'
    version: '2.2.202'
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build API ($(buildConfiguration))'

- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: '**/*UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# TODO: This does not work (yet) due to a 404 error when seeding the DynamoDB database
# - task: DotNetCoreCLI@2
#   displayName: Run Integration Tests
#   inputs:
#     command: test
#     projects: '**/*IntegrationTests/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'artifact' 
    publishLocation: 'Container'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'AWS'
    regionName: 'eu-west-1'
    stackName: 'ManufacturingApiStack'
    templateFile: 'ManufacturingAPI/serverless.template'
    capabilityIAM: 'true'
    capabilityNamedIAM: 'true'
